version: '1'

services:
  local_clothes_store_db:
    container_name: local_clothes_store_db
    image: postgres:13.1-alpine
    ports:
      - '5000:5432'
    env_file:
      - local.env
    volumes:
      - local_clothes_store_database:/var/lib/postgresql/data
      - ./local.init:/docker-entrypoint-initdb.d
      

  local_clothes_store_api:
    container_name: local_clothes_store_api
    image: 'node:lts'
    working_dir: /usr/api
    ports:
      - '5001:3000'
    command: bash -c "npm run start:debug"
    env_file:
      - local.env
    depends_on:
      - local_clothes_store_db
    volumes:
      - ./:/usr/api

volumes:
  local_clothes_store_database: {}
